# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-14 18:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField(default=0)),
                ('date', models.DateField(default=datetime.date(2017, 4, 14))),
                ('time_in', models.TimeField(default=datetime.time(23, 50, 8, 478239))),
                ('time_out', models.TimeField(default=datetime.time(23, 50, 8, 478239))),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
