# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-14 18:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20170414_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='time_in',
            field=models.TimeField(default=datetime.time(23, 58, 33, 75270)),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='time_out',
            field=models.TimeField(default=datetime.time(23, 58, 33, 75270)),
        ),
    ]
