# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-14 20:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_auto_20170415_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='time_in',
            field=models.TimeField(default=datetime.time(2, 2, 13, 835946)),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='time_out',
            field=models.TimeField(default=datetime.time(2, 2, 13, 835946)),
        ),
    ]
